
version: '2'
services:
    apache:
        image: x3rus/vhost_test_aws
        container_name : 'test_aws'
        #        build: .
        hostname: apache.x3rus.com
        environment:
            - BDPI_USER=pi_usr
            - BDPI_PASS=314
            - BDPI_DATABASE=pi
            - BDPI_ADDR=172.24.0.3
            - BDCON_USER=con_usr
            - BDCON_PASS=tact
            - BDCON_DATABASE=people
            - BDCON_ADDR=172.24.0.2
    #   port:
    #       3306:3306

