version: '2'
services:
    ansible-srv:
        image: x3rus/x3-ansible
        build: ./x3-ansible-srv/
        container_name : 'x3-ansible-p'
        environment:
            - TERM=xterm
        links:
            - ansible-app:appserver
        entrypoint: 'tail -f /dev/null'
#        volumes:
    ansible-app:
        image: x3rus/x3-ansible-client
        build: ./x3-ansible-client/
        container_name : 'x3-ansible-appsrv-t'
        environment:
            - TERM=xterm


# Exemple d'utilisation avec docker-compose et run :
# docker-compose run --volume=/tmp/ansible-tmp/:/etc/ansible/  ansible   /etc/ansible/playbooks/setup-dck.yml
#
