version: '2'
services:
    db-contact:
        image: mysql:5.5
        container_name : 'showcontact'
        hostname: dbcontact.x3rus.com
        environment:
            - MYSQL_USER=con_usr
            - MYSQL_PASSWORD=tact
            - MYSQL_DATABASE=people
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - TZ=America/Montreal
            - TERM=xterm
       ports:
           3306:3306

