version: '2'
services:
    db-coco:
        image: mysql:5.5
        restart: unless-stopped
        container_name : 'coco-db-t'
        hostname: db.coco.com
        environment:
            - MYSQL_USER=umail
            - MYSQL_PASSWORD=ZePassword
            - MYSQL_DATABASE=vmail
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - TZ=America/Montreal
            - TERM=xterm
#        volumes:
#            - /srv/docker/coco-db-t/var_lib_mysql:/var/lib/mysql
    http-coco:
        image: postfixadmin
        build: ./http/
        restart: unless-stopped
        container_name : 'coco-http-t'
        hostname: mail.coco.com
        links:
            - db-coco:db
        environment:
            - MYSQL_USER=umail
            - MYSQL_PASSWORD=ZePassword
            - MYSQL_DATABASE=vmail
            - TZ=America/Montreal
            - TERM=xterm
            - DB_TYPE=mysql
            - MAIL_DOMAIN=coco.com
            - SETUP_PASS=superPasse
            - ADM_MAIL=admin@coco.com
            - ADM_PASS=DockerRock
    smtp-coco:
        image: smtp-db
        build: ./smtp/
        restart: unless-stopped
        container_name : 'coco-smtp-t'
        hostname: mail.coco.com
        links:
            - db-coco:db
            - imap-coco:dovecot-lmtp
        environment:
            - MYSQL_USER=umail
            - MYSQL_PASSWORD=ZePassword
            - MYSQL_DATABASE=vmail
            - TZ=America/Montreal
            - TERM=xterm
    imap-coco:
        image: imap-db
        build: ./imap/
        restart: unless-stopped
        container_name : 'coco-imap-t'
        hostname: mail.coco.com
        links:
            - db-coco:db
        environment:
            - MYSQL_USER=umail
            - MYSQL_PASSWORD=ZePassword
            - MYSQL_DATABASE=vmail
            - TZ=America/Montreal
            - TERM=xterm
 
