version: '2'
services:
    db-coco:
        image: mysql:5.5
        restart: unless-stopped
        container_name : 'coco-db-t'
        hostname: db.coco.com
        environment:
            - MYSQL_USER=umail
            - MYSQL_PASSWORD=ZePassword
            - MYSQL_DATABASE=vmail
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - TZ=America/Montreal
            - TERM=xterm
        volumes:
            - /srv/docker/coco-db-t/var_lib_mysql:/var/lib/mysql
    http-coco:
        image: postfixadmin
        build: ./http/
        restart: unless-stopped
        container_name : 'coco-http-t'
        hostname: mail.coco.com
        links:
            - db-coco:db
        environment:
            - MYSQL_USER=umail
            - MYSQL_PASSWORD=ZePassword
            - MYSQL_DATABASE=vmail
            - TZ=America/Montreal
            - TERM=xterm
